---
title: "BIOL1001-001: Forest of the Future Lab"
author: "Charlie Willis"
date: "04/20/2019"
output: html_document
---

```{r STEP 1: Setup R, include=FALSE}
# Install and load necessary packages
install.packages(c('rgbif','dismo','ggplot2','httr','rgeos'),dependencies=T, source = T)

library(dismo)
library(ggplot2)
library(rgeos)
library(rgbif)
library(httr)

# Set proxy configurations for UMN Network
set_config(use_proxy(url = "proxy.oit.umn.edu", port = 3128))

```

```{r STEP 2: Importing global climate data}
# Import current and future environmental data
# www.worldclim.org
  predictors = getData("worldclim",var="bio",res=10)
  he85_70 = getData('CMIP5', var='bio', res=10, rcp=85, model='HE', year=70) # UK Met Office
    names(he85_70) = names(predictors)
  cc85_70 = getData('CMIP5', var='bio', res=10, rcp=85, model='CC', year=70) # US National Center for Atmospheric Research
    names(cc85_70) = names(predictors)
  gs85_70 = getData('CMIP5', var='bio', res=10, rcp=85, model='GS', year=70) # NASA Goddard Institute for Space Studies
    names(gs85_70) = names(predictors)
  bc85_70 = getData('CMIP5', var='bio', res=10, rcp=85, model='BC', year=70) # China Beijing Climate Center
    names(bc85_70) = names(predictors)
```

```{r STEP 3: Comparing global climate models}
# Plot current and future (2070) mean annual temperature
breaks <- seq(-200, 350, by=10)
colBIO1 = colorRampPalette(c("#313695","#74add1","#ffffbf","#f46d43","#a50026"))(length(breaks))
arg = list(at=c(-200,-100,0,100,200,300,400), labels=c('-20','-10','0','10','20','30','40'))
plot(predictors[[1]], main = 'Mean Annual Temperature (C) - Current',xlab='longitude',ylab='latitude', breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
plot(he85_70[[1]], main = 'Mean Annual Temperature (C) - 2070 (RCP8.5|UK Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
#plot(cc85_70[[1]], main = 'Mean Annual Temperature (C) - 2070 (RCP8.5|US NCAR Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
#plot(gs85_70[[1]], main = 'Mean Annual Temperature (C) - 2070 (RCP8.5|US NASA Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
#plot(bc85_70[[1]], main = 'Mean Annual Temperature (C) - 2070 (RCP8.5|China Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)

# Plot current and future (2070) total precipitation
breaks <- seq(0, 6000, by=1000)
colBIO12 = colorRampPalette(c("#eff3ff","#bdd7e7","#6baed6","#3182bd","#08519c"))(length(breaks))
arg = list(at=c(0,1000,2000,3000,4000,5000,6000), labels=c('0','1000','2000','3000','4000','5000','6000'))
plot(predictors[[12]], main = 'Total Annual Precipitation (mm) - Current',xlab='longitude',ylab='latitude', breaks = breaks, col=colBIO12 ,zlim=c(0, 6000),axis.args=arg)
plot(he85_70[[12]], main = 'Total Annual Precipitation (mm) - 2070 (RCP8.5|UK Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO12 ,zlim=c(0, 6000),axis.args=arg)
#plot(cc85_70[[12]], main = 'Total Annual Precipitation (mm) - 2070 (RCP8.5|US NCAR Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO12 ,zlim=c(0, 6000),axis.args=arg)
#plot(gs85_70[[12]], main = 'Total Annual Precipitation (mm) - 2070 (RCP8.5|US NASA Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO12 ,zlim=c(0, 6000),axis.args=arg)
#plot(bc85_70[[12]], main = 'Total Annual Precipitation (mm) - 2070 (RCP8.5|China Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO12 ,zlim=c(0, 6000),axis.args=arg)

# Compare mean change in global temperate between present and 2070
set.seed(100)
bg = randomPoints(predictors[[1]],5000)

# Extract a random subsample of global climate data for comparison
bg_gb_current = as.data.frame(extract(predictors,bg))
bg_gb_he85_70 = as.data.frame(extract(he85_70,bg))
bg_gb_cc85_70 = as.data.frame(extract(cc85_70,bg))
bg_gb_gs85_70 = as.data.frame(extract(gs85_70,bg))
bg_gb_bc85_70 = as.data.frame(extract(bc85_70,bg))

bg_gb_current$name  = 'Current'
bg_gb_he85_70$name  = '2070|UK'
bg_gb_cc85_70$name  = '2070|NCAR'
bg_gb_gs85_70$name  = '2070|NASA'
bg_gb_bc85_70$name  = '2070|China'

bg_gb_comp = rbind(bg_gb_current,bg_gb_he85_70,bg_gb_cc85_70,bg_gb_gs85_70,bg_gb_bc85_70)
bg_gb_comp$name = factor(bg_gb_comp$name, levels=c("Current","2070|UK","2070|NCAR","2070|NASA","2070|China")) # reorder factors

# Plot comparison in change in mean annual temperature
boxplot((bio1/10)~name, data=bg_gb_comp, notch=F,col=(c('#78c679','#f4cae4','#fdcdac','#fbb4ae','#ffff99')),ylab="Mean Annual Temperature (C)",main="Change in Global Mean Annual Temperature")
text(2,25,paste("+",round((mean(bg_gb_he85_70$bio1)-mean(bg_gb_current$bio1))/10,2),"C",sep=''))
text(3,25,paste("+",round((mean(bg_gb_cc85_70$bio1)-mean(bg_gb_current$bio1))/10,2),"C",sep=''))
text(4,25,paste("+",round((mean(bg_gb_gs85_70$bio1)-mean(bg_gb_current$bio1))/10,2),"C",sep=''))
text(5,25,paste("+",round((mean(bg_gb_bc85_70$bio1)-mean(bg_gb_current$bio1))/10,2),"C",sep=''))

# Plot comparison in change in total annual precipitation
boxplot((bio12)~name, data=bg_gb_comp, notch=F,col=(c('#78c679','#f4cae4','#fdcdac','#fbb4ae','#ffff99')),ylab="Total Annual Precipitation (mm)",main="Change in Total Annual Precipitation")
text(2,6250,paste("+",round((mean(bg_gb_he85_70$bio12)-mean(bg_gb_current$bio12)),2),"mm",sep=''))
text(3,6250,paste("+",round((mean(bg_gb_cc85_70$bio12)-mean(bg_gb_current$bio12)),2),"mm",sep=''))
text(4,6250,paste("+",round((mean(bg_gb_gs85_70$bio12)-mean(bg_gb_current$bio12)),2),"mm",sep=''))
text(5,6250,paste("+",round((mean(bg_gb_bc85_70$bio12)-mean(bg_gb_current$bio12)),2),"mm",sep=''))
```

```{r STEP 5: Compare climate change in North America and Minnesota}
# Crop the global climate maps to only North America
e = extent(-175, -45, 14.5, 83.5)
predictors = crop(predictors,e)
he85_70 = crop(he85_70,e)
cc85_70 = crop(cc85_70,e)
gs85_70 = crop(gs85_70,e)
bc85_70 = crop(bc85_70,e)

# Crop climate variables for Minnesota
  us = getData("GADM",country="USA",level=1)
  mn = us[us$NAME_1 %in% 'Minnesota',]
  x = mask(predictors,mn)
  y = crop(x,mn)
  predictorsMN = crop(mask(predictors,mn),mn)
  he85_70MN    = crop(mask(he85_70,mn),mn)
  cc85_70MN    = crop(mask(cc85_70,mn),mn)
  gs85_70MN    = crop(mask(gs85_70,mn),mn)
  bc85_70MN    = crop(mask(bc85_70,mn),mn)
  

# Plot current and future (2070) mean annual temperature
breaks <- seq(-200, 350, by=10)
colBIO1 = colorRampPalette(c("#313695","#74add1","#ffffbf","#f46d43","#a50026"))(length(breaks))
arg = list(at=c(-200,-100,0,100,200,300,400), labels=c('-20','-10','0','10','20','30','40'))
plot(predictors[[1]], main = 'Mean Annual Temperature (C) - Current',xlab='longitude',ylab='latitude', breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
plot(he85_70[[1]], main = 'Mean Annual Temperature (C) - 2070 (RCP8.5|UK Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
#plot(cc85_70[[1]], main = 'Mean Annual Temperature (C) - 2070 (RCP8.5|US NCAR Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
#plot(gs85_70[[1]], main = 'Mean Annual Temperature (C) - 2070 (RCP8.5|US NASA Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
#plot(bc85_70[[1]], main = 'Mean Annual Temperature (C) - 2070 (RCP8.5|China Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)

# Plot current and future (2070) total precipitation
breaks <- seq(0, 3000, by=500)
colBIO12 = colorRampPalette(c("#eff3ff","#bdd7e7","#6baed6","#3182bd","#08519c"))(length(breaks))
arg = list(at=c(0,500,1000,1500,2000,2500,3000), labels=c('0','500','1000','1500','2000','2500','3000'))
plot(predictors[[12]], main = 'Total Annual Precipitation (mm) - Current',xlab='longitude',ylab='latitude', breaks = breaks, col=colBIO12 ,zlim=c(0, 3000),axis.args=arg)
plot(he85_70[[12]], main = 'Total Annual Precipitation (mm) - 2070 (RCP8.5|UK Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO12 ,zlim=c(0, 3000),axis.args=arg)
#plot(cc85_70[[12]], main = 'Total Annual Precipitation (mm) - 2070 (RCP8.5|US NCAR Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO12 ,zlim=c(0, 3000),axis.args=arg)
#plot(gs85_70[[12]], main = 'Total Annual Precipitation (mm) - 2070 (RCP8.5|US NASA Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO12 ,zlim=c(0, 3000),axis.args=arg)
#plot(bc85_70[[12]], main = 'Total Annual Precipitation (mm) - 2070 (RCP8.5|China Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO12 ,zlim=c(0, 3000),axis.args=arg)

# Compare mean change in global temperate between present and 2070
set.seed(100)
bg = randomPoints(predictors[[1]],1000)

# Extract a random subsample of global climate data for comparison
bg_gb_current = as.data.frame(extract(predictors,bg))
bg_gb_he85_70 = as.data.frame(extract(he85_70,bg))
bg_gb_cc85_70 = as.data.frame(extract(cc85_70,bg))
bg_gb_gs85_70 = as.data.frame(extract(gs85_70,bg))
bg_gb_bc85_70 = as.data.frame(extract(bc85_70,bg))

bg_gb_current$name  = 'Current'
bg_gb_he85_70$name  = '2070|UK'
bg_gb_cc85_70$name  = '2070|NCAR'
bg_gb_gs85_70$name  = '2070|NASA'
bg_gb_bc85_70$name  = '2070|China'

bg_gb_comp = rbind(bg_gb_current,bg_gb_he85_70,bg_gb_cc85_70,bg_gb_gs85_70,bg_gb_bc85_70)
bg_gb_comp$name = factor(bg_gb_comp$name, levels=c("Current","2070|UK","2070|NCAR","2070|NASA","2070|China")) # reorder factors

# Plot comparison in change in mean annual temperature
boxplot((bio1/10)~name, data=bg_gb_comp, notch=F,col=(c('#78c679','#f4cae4','#fdcdac','#fbb4ae','#ffff99')),ylab="Mean Annual Temperature (C)",main="Change in Mean Annual Temperature (North America)")
text(2,10,paste("+",round((mean(bg_gb_he85_70$bio1)-mean(bg_gb_current$bio1))/10,2),"C",sep=''))
text(3,10,paste("+",round((mean(bg_gb_cc85_70$bio1)-mean(bg_gb_current$bio1))/10,2),"C",sep=''))
text(4,10,paste("+",round((mean(bg_gb_gs85_70$bio1)-mean(bg_gb_current$bio1))/10,2),"C",sep=''))
text(5,10,paste("+",round((mean(bg_gb_bc85_70$bio1)-mean(bg_gb_current$bio1))/10,2),"C",sep=''))

# Plot comparison in change in total annual precipitation
boxplot((bio12)~name, data=bg_gb_comp, notch=F,col=(c('#78c679','#f4cae4','#fdcdac','#fbb4ae','#ffff99')),ylab="Total Annual Precipitation (mm)",main="Change in Total Annual Precipitation (North America)")
text(2,3500,paste("+",round((mean(bg_gb_he85_70$bio12)-mean(bg_gb_current$bio12)),2),"mm",sep=''))
text(3,3500,paste("+",round((mean(bg_gb_cc85_70$bio12)-mean(bg_gb_current$bio12)),2),"mm",sep=''))
text(4,3500,paste("+",round((mean(bg_gb_gs85_70$bio12)-mean(bg_gb_current$bio12)),2),"mm",sep=''))
text(5,3500,paste("+",round((mean(bg_gb_bc85_70$bio12)-mean(bg_gb_current$bio12)),2),"mm",sep=''))

#------------------------------------
# COMPARE CLIMATE CHANGE IN MINNESOTA
# Plot current and future (2070) mean annual temperature
breaks <- seq(-200, 350, by=10)
colBIO1 = colorRampPalette(c("#313695","#74add1","#ffffbf","#f46d43","#a50026"))(length(breaks))
arg = list(at=c(-200,-100,0,100,200,300,400), labels=c('-20','-10','0','10','20','30','40'))
plot(predictorsMN[[1]], main = 'Mean Annual Temperature (C) - Current',xlab='longitude',ylab='latitude', breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
plot(he85_70MN[[1]], main = 'Mean Annual Temperature (C) - 2070 (RCP8.5|UK Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
#plot(cc85_70MN[[1]], main = 'Mean Annual Temperature (C) - 2070 (RCP8.5|US NCAR Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
#plot(gs85_70MN[[1]], main = 'Mean Annual Temperature (C) - 2070 (RCP8.5|US NASA Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
#plot(bc85_70MN[[1]], main = 'Mean Annual Temperature (C) - 2070 (RCP8.5|China Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)

# Plot current and future (2070) total precipitation
breaks <- seq(0, 1200, by=200)
colBIO12 = colorRampPalette(c("#eff3ff","#bdd7e7","#6baed6","#3182bd","#08519c"))(length(breaks))
arg = list(at=c(0,200,400,600,800,1000,1200), labels=c('0','200','400','600','800','1000','1200'))
plot(predictorsMN[[12]], main = 'Total Annual Precipitation (mm) - Current',xlab='longitude',ylab='latitude', breaks = breaks, col=colBIO12 ,zlim=c(0, 1200),axis.args=arg)
plot(he85_70MN[[12]], main = 'Total Annual Precipitation (mm) - 2070 (RCP8.5|UK Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO12 ,zlim=c(0, 1200),axis.args=arg)
#plot(cc85_70MN[[12]], main = 'Total Annual Precipitation (mm) - 2070 (RCP8.5|US NCAR Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO12 ,zlim=c(0, 1200),axis.args=arg)
#plot(gs85_70MN[[12]], main = 'Total Annual Precipitation (mm) - 2070 (RCP8.5|US NASA Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO12 ,zlim=c(0, 1200),axis.args=arg)
#plot(bc85_70MN[[12]], main = 'Total Annual Precipitation (mm) - 2070 (RCP8.5|China Model)',xlab='longitude',ylab='latitude',breaks = breaks, col=colBIO12 ,zlim=c(0, 1200),axis.args=arg)

# Compare mean change in global temperate between present and 2070
set.seed(100)
bg = randomPoints(predictorsMN[[1]],1000)

# Extract a random subsample of global climate data for comparison
bg_gb_currentMN = as.data.frame(extract(predictorsMN,bg,na.rm=TRUE))
bg_gb_he85_70MN = as.data.frame(extract(he85_70MN,bg,na.rm=TRUE))
bg_gb_cc85_70MN = as.data.frame(extract(cc85_70MN,bg,na.rm=TRUE))
bg_gb_gs85_70MN = as.data.frame(extract(gs85_70MN,bg,na.rm=TRUE))
bg_gb_bc85_70MN = as.data.frame(extract(bc85_70MN,bg,na.rm=TRUE))

bg_gb_currentMN$name  = 'Current'
bg_gb_he85_70MN$name  = '2070|UK'
bg_gb_cc85_70MN$name  = '2070|NCAR'
bg_gb_gs85_70MN$name  = '2070|NASA'
bg_gb_bc85_70MN$name  = '2070|China'

bg_gb_comp = rbind(bg_gb_currentMN,bg_gb_he85_70MN,bg_gb_cc85_70MN,bg_gb_gs85_70MN,bg_gb_bc85_70MN)
bg_gb_comp$name = factor(bg_gb_comp$name, levels=c("Current","2070|UK","2070|NCAR","2070|NASA","2070|China")) # reorder factors

# Plot comparison in change in mean annual temperature
boxplot((bio1/10)~name, data=bg_gb_comp, notch=F,col=(c('#78c679','#f4cae4','#fdcdac','#fbb4ae','#ffff99')),ylab="Mean Annual Temperature (C)",main="Change in Mean Annual Temperature (Minnesota)")
text(2,13,paste("+",round((mean(bg_gb_he85_70MN$bio1)-mean(bg_gb_current$bio1))/10,2),"C",sep=''))
text(3,13,paste("+",round((mean(bg_gb_cc85_70MN$bio1)-mean(bg_gb_current$bio1))/10,2),"C",sep=''))
text(4,13,paste("+",round((mean(bg_gb_gs85_70MN$bio1)-mean(bg_gb_current$bio1))/10,2),"C",sep=''))
text(5,13,paste("+",round((mean(bg_gb_bc85_70MN$bio1)-mean(bg_gb_current$bio1))/10,2),"C",sep=''))

# Plot comparison in change in total annual precipitation
boxplot((bio12)~name, data=bg_gb_comp, notch=F,col=(c('#78c679','#f4cae4','#fdcdac','#fbb4ae','#ffff99')),ylab="Total Annual Precipitation (mm)",main="Change in Total Annual Precipitation (Minnesota)")
text(2,900,paste("+",round((mean(bg_gb_he85_70MN$bio12)-mean(bg_gb_current$bio12)),2),"mm",sep=''))
text(3,900,paste("+",round((mean(bg_gb_cc85_70MN$bio12)-mean(bg_gb_current$bio12)),2),"mm",sep=''))
text(4,900,paste("+",round((mean(bg_gb_gs85_70MN$bio12)-mean(bg_gb_current$bio12)),2),"mm",sep=''))
text(5,900,paste("+",round((mean(bg_gb_bc85_70MN$bio12)-mean(bg_gb_current$bio12)),2),"mm",sep=''))
```

```{r STEP 5: Import species distribution data}
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! #
# ENTER YOUR SPECIES NAMES HERE:
species1 = 'Quercus alba'
species2 = 'Acer rubrum'
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! #


# Import species distribution data from GBIF
# Limits download to 5000 specimen records per species
dat = occ_search(scientificName=c(species1,species2), limit=10000, return = 'data', hasCoordinate = T)

# Edit occurrence data for species 1
sp1 = as.data.frame(dat[[1]])
sp1 = sp1[,c('name','decimalLongitude','decimalLatitude')]
sp1 = subset(sp1,name==names(sort(table(sp1$name),decreasing=TRUE))[[1]])
names(sp1) = c('species','lon','lat')
coordinates(sp1)  = c('lon','lat')
crs(sp1) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 ")
sp1_coords = crop(sp1, e)
sp1 = as.data.frame(sp1_coords)
sp1_coordsMN = sp1_coords[complete.cases((over(sp1_coords,mn))),]

# Edit occurrence data for species 2
sp2 = as.data.frame(dat[[2]])
sp2 = sp2[,c('name','decimalLongitude','decimalLatitude')]
sp2 = subset(sp2,name==names(sort(table(sp2$name),decreasing=TRUE))[[1]])
names(sp2) = c('species','lon','lat')
coordinates(sp2)  = c('lon','lat')
crs(sp2) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 ")
sp2_coords = crop(sp2, e)
sp2 = as.data.frame(sp2_coords)
sp2_coordsMN = sp2_coords[complete.cases(over(sp2_coords,mn)),]

occData = rbind(sp1,sp2)

# Plot species distribution data
### Plot species occurrences for North America
col1 = '#ffcc33'
col2 = '#7a0019'

# Species distribution in North America over mean annual temperature
breaks <- seq(-200, 350, by=10)
colBIO1 = colorRampPalette(c("#313695","#74add1","#ffffbf","#f46d43","#a50026"))(length(breaks))
arg = list(at=c(-200,-100,0,100,200,300,400), labels=c('-20','-10','0','10','20','30','40'))
plot(predictors[[1]], main = paste('Distribution of',species1,"and",species2,'in NA (over mean annual temp)',sep = ' '),xlab='longitude',ylab='latitude', breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
plot(mn,add=T)
points(sp1_coords, pch=19, col=col1, cex=0.5)
points(sp2_coords, pch=18, col=col2, cex=0.7)
legend(-180,30, legend=c(species1, species2), col=c(col1,col2), pch=c(19,18), cex=0.8)

# Species distribution in Minnesota over mean annual temperature
plot(predictorsMN[[1]], main = paste('Distribution of',species1,"and",species2,'in Minnesota',sep = ' '),xlab='longitude',ylab='latitude', breaks = breaks, col=colBIO1 ,zlim=c(-200, 350),axis.args=arg)
plot(mn,add=T)
points(gIntersection(sp1_coords,mn), pch=19, col=col1, cex=0.5)
points(gIntersection(sp2_coords,mn), pch=18, col=col2, cex=0.7)
legend(-91,45, legend=c(species1, species2), col=c(col1,col2), pch=c(19,18), cex=0.8)

```

```{r STEP 6: Characterize species climate niche}
# Set what variables to compare
# We will be comparing Mean Annual Temperature (BIO1) & Total Annual Precipitation (BIO12)
# Variable List: http://www.worldclim.org/bioclim
var1 = 'bio1' 
var2 = 'bio12'
var1.name = "Mean Annual Temperature (C)"
var2.name = "Total Annual Precipitation (mm)"

# Extract current climate data for each species
sp1_clim = as.data.frame(extract(predictors,sp1_coords))
  sp1_clim = na.omit(sp1_clim)
sp2_clim = as.data.frame(extract(predictors,sp2_coords))
  sp2_clim = na.omit(sp2_clim)
  
# Generate 5000 random background dataset of NA climate
set.seed(100)
bg = randomPoints(predictors[[1]],5000)

# Extract climate data for background points
bg_clim = as.data.frame(extract(predictors,bg))

bg_clim$name  = 'background'
sp1_clim$name = species1
sp2_clim$name = species2
sp_clim = rbind(sp1_clim,sp2_clim,bg_clim)
sp_clim$name = factor(sp_clim$name, levels=c(species1, species2, "background")) # reorder factors

plot(bg_clim[,var1],bg_clim[,var2],xlim=rev(range(bg_clim[,var1])),xlab=var1.name, ylab=var2.name, pch = 19, col='grey', cex = 0.5, main="Climate variation across North America")
  hpts <- chull(bg_clim[,c(var1,var2)])
  hpts <- c(hpts, hpts[1])
  lines(bg_clim[,c(var1,var2)][hpts, ],col = 'grey')
  points(sp1_clim[,var1],sp1_clim[,var2],pch=19,col=col1,cex=0.75)
    hpts <- chull(sp1_clim[,c(var1,var2)])
    hpts <- c(hpts, hpts[1])
    lines(sp1_clim[,c(var1,var2)][hpts, ],col = col1)
  points(sp2_clim[,var1],sp2_clim[,var2],pch=18,col=col2,cex=0.75)
    hpts <- chull(sp2_clim[,c(var1,var2)])
    hpts <- c(hpts, hpts[1])
    lines(sp2_clim[,c(var1,var2)][hpts, ],col = col2)
    
# Add legend to the plot
  points(min(bg_clim[,var1])*.45,max(bg_clim[,var2])*.95, pch=19, col=col1, cex=1)
  text(min(bg_clim[,var1])*.45,max(bg_clim[,var2])*.95,species1, pos=4, font = 3)
  points(min(bg_clim[,var1])*.45,max(bg_clim[,var2])*.9, pch=18, col=col2, cex=1)
  text(min(bg_clim[,var1])*.45,max(bg_clim[,var2])*.9,species2, pos=4, font = 3)
  points(min(bg_clim[,var1])*.45,max(bg_clim[,var2])*.85, pch=19, col='grey', cex=1)
  text(min(bg_clim[,var1])*.45,max(bg_clim[,var2])*.85,'Variation across NA', pos=4)

sp_clim_sub = subset(sp_clim,!name=='background')
sp_clim_sub$name = sp_clim_sub$name[ , drop=TRUE]
boxplot(sp_clim_sub[,var1]/10~name, data=sp_clim_sub, notch=F,col=(c(col1,col2)),main=var1.name,ylab=var1.name)
boxplot(sp_clim_sub[,var2]~name, data=sp_clim_sub,notch=F,col=(c(col1,col2)),main=var2.name,ylab=var2.name)
```

```{r STEP 7: Generate species distribution models}
set.seed(0)

# Generate background points for comparison
backg <- randomPoints(predictors, n=30000)
group <- kfold(backg, 5)
backg_train <- backg[group != 1, ]
backg_test <- backg[group == 1, ]

# SDM for Species 1
group <- kfold(sp1_coords, 5)
pres_train1 <- sp1_coords[group != 1, ]
pres_test1 <- sp1_coords[group == 1, ]

pre1 <- bioclim(predictors, pres_train1)
  ep1 <- evaluate(pres_test1, backg_test, pre1, predictors)
  tr1 <- threshold(ep1, 'spec_sens')
  plot(ep1, 'ROC')
  text(0.5,0.2,species1)

# SDM for Species 2
group <- kfold(sp2_coords, 5)
pres_train2 <- sp2_coords[group != 1, ]
pres_test2 <- sp2_coords[group == 1, ]

pre2 <- bioclim(predictors, pres_train2)
  ep2 <- evaluate(pres_test2, backg_test, pre2, predictors)
  tr2 <- threshold(ep2, 'spec_sens')
  plot(ep2, 'ROC')
  text(0.5,0.2,species2)
```  


```{r STEP 8: Use model to predict current and future suitable habitat for North America}
# Predict distribtuion of species suitable habitat using SDMs
  pb_cur_sp1 <- predict(predictors, pre1, progress='')
  pb_fut_sp1 <- predict(he85_70, pre1, progress='')
  
  pb_cur_sp2 <- predict(predictors, pre2, progress='')
  pb_fut_sp2 <- predict(he85_70, pre2, progress='')
  
# Convert model outputs to presence/absence of suitable habitat
  sp1_threshMatrix = matrix(c(0,tr1,0,tr1,1,1),ncol=3, byrow=TRUE)
  sp2_threshMatrix = matrix(c(0,tr2,0,tr2,1,1),ncol=3, byrow=TRUE)
  
  pb_cur_sp1 = reclassify(pb_cur_sp1, sp1_threshMatrix)
  pb_fut_sp1 = reclassify(pb_fut_sp1, sp1_threshMatrix)
    
  pb_cur_sp2 = reclassify(pb_cur_sp2, sp2_threshMatrix)
  pb_fut_sp2 = reclassify(pb_fut_sp2, sp2_threshMatrix)
  
# Plot current and future distributions in North America
    plot(pb_cur_sp1,main = paste('Current NA distribution of suitable habitat for',species1,sep = ' '), xlab='longitude',ylab='latitude')
      plot(mn,add=T,lwd=1)
    plot(pb_fut_sp1,main = paste('2070 NA distribution of suitable habitat for',species1,sep = ' '), xlab='longitude',ylab='latitude')
      plot(mn,add=T,lwd=1)
    plot(pb_cur_sp2,main = paste('Current NA distribution of suitable habitat for',species2,sep = ' '), xlab='longitude',ylab='latitude')
      plot(mn,add=T,lwd=1)
    plot(pb_fut_sp2,main = paste('2070 NA distribution of suitable habitat for',species2,sep = ' '), xlab='longitude',ylab='latitude')
      plot(mn,add=T,lwd=1)
```

```{r STEP 9: Use model to predict current and future suitable habitat in Minnesota}
# Predict distribtuion of species suitable habitat in Minnesota
  pb_cur_sp1MN    = crop(mask(pb_cur_sp1,mn),mn)
  pb_fut_sp1MN    = crop(mask(pb_fut_sp1,mn),mn)
  pb_cur_sp2MN    = crop(mask(pb_cur_sp2,mn),mn)
  pb_fut_sp2MN    = crop(mask(pb_fut_sp2,mn),mn)
  
# Plot current and future distributions in North America
    plot(pb_cur_sp1MN,main = paste('Current MN distribution of suitable habitat for',species1,sep = ' '), xlab='longitude',ylab='latitude')
      plot(mn,add=T,lwd=1)
    plot(pb_fut_sp1MN,main = paste('2070 MN distribution of suitable habitat for',species1,sep = ' '), xlab='longitude',ylab='latitude')
      plot(mn,add=T,lwd=1)
    plot(pb_cur_sp2MN,main = paste('Current MN distribution of suitable habitat for',species2,sep = ' '), xlab='longitude',ylab='latitude')
      plot(mn,add=T,lwd=1)
    plot(pb_fut_sp2MN,main = paste('2070 MN distribution of suitable habitat for',species2,sep = ' '), xlab='longitude',ylab='latitude')
      plot(mn,add=T,lwd=1)
```

```{r STEP 9: Analysis Species Distribution Model Outputs}
# Calculate summary statistics for North America
  sp1.net.change.NA.2070 = round(((cellStats(pb_fut_sp1,'sum') - cellStats(pb_cur_sp1,'sum'))/cellStats(pb_cur_sp1,'sum') * 100),2)
  sp2.net.change.NA.2070 = round(((cellStats(pb_fut_sp2,'sum') - cellStats(pb_cur_sp2,'sum'))/cellStats(pb_cur_sp2,'sum') * 100),2)

  sp1.loss.NA.2070 = pb_cur_sp1 - pb_fut_sp1
  sp1.loss.NA.2070[sp1.loss.NA.2070 == -1] = 0
  sp1.loss.NA.2070 = round(cellStats(sp1.loss.NA.2070,'sum')/cellStats(pb_cur_sp1,'sum')*100,2)

  sp2.loss.NA.2070 = pb_cur_sp2 - pb_fut_sp2
  sp2.loss.NA.2070[sp2.loss.NA.2070 == -1] = 0
  sp2.loss.NA.2070 = round(cellStats(sp2.loss.NA.2070,'sum')/cellStats(pb_cur_sp2,'sum')*100,2)
  
# Calculate summary statistics for Minnesota
  sp1.net.change.MN.2070 = round(((cellStats(pb_fut_sp1MN,'sum') - cellStats(pb_cur_sp1MN,'sum'))/cellStats(pb_cur_sp1MN,'sum') * 100),2)
  sp2.net.change.MN.2070 = round(((cellStats(pb_fut_sp2MN,'sum') - cellStats(pb_cur_sp2MN,'sum'))/cellStats(pb_cur_sp2MN,'sum') * 100),2)

  sp1.loss.MN.2070 = pb_cur_sp1MN - pb_fut_sp1MN
  sp1.loss.MN.2070[sp1.loss.MN.2070 == -1] = 0
  sp1.loss.MN.2070 = round(cellStats(sp1.loss.MN.2070,'sum')/cellStats(pb_cur_sp1MN,'sum')*100,2)

  sp2.loss.MN.2070 = pb_cur_sp2MN - pb_fut_sp2MN
  sp2.loss.MN.2070[sp2.loss.MN.2070 == -1] = 0
  sp2.loss.MN.2070 = round(cellStats(sp2.loss.MN.2070,'sum')/cellStats(pb_cur_sp2MN,'sum')*100,2)
  
# Plot summary of % Net Change in Suitable Habitat
sp1_summary = as.data.frame(c(sp1.net.change.NA.2070,sp1.net.change.MN.2070))
sp1_summary$year  = as.character(c(2070,2070))
sp1_summary$level = c('NA','MN')
names(sp1_summary) = c('Percent.Change','Year','Region')

sp1_net_plot = ggplot(sp1_summary, aes(fill=Year, y=Percent.Change, x=Region)) + 
     geom_bar(position="dodge", stat="identity", fill = col1) +
     scale_fill_manual(values=c('#fc9272','#de2d26')) +
      theme(axis.text.x = element_text(face = "bold", size = 14)) +
      theme(axis.text.y = element_text(face = "bold", size = 14)) +
      theme(axis.title = element_text(face = "bold", size = 16)) + 
      theme(plot.title = element_text(face = "bold.italic", size = 24)) +
      ggtitle(species1) + labs(y="% Net Change in Suitable Habitat")
sp1_net_plot

sp2_summary = as.data.frame(c(sp2.net.change.NA.2070,sp2.net.change.MN.2070))
sp2_summary$year  = as.character(c(2070,2070))
sp2_summary$level = c('NA','MN')
names(sp2_summary) = c('Percent.Change','Year','Region')

sp2_net_plot = ggplot(sp2_summary, aes(fill=Year, y=Percent.Change, x=Region)) + 
     geom_bar(position="dodge", stat="identity", fill = col2) +
     scale_fill_manual(values=c('#fc9272','#de2d26')) +
      theme(axis.text.x = element_text(face = "bold", size = 14)) +
      theme(axis.text.y = element_text(face = "bold", size = 14)) +
      theme(axis.title = element_text(face = "bold", size = 16)) + 
      theme(plot.title = element_text(face = "bold.italic", size = 24)) +
      ggtitle(species2) + labs(y="% Net Change in Suitable Habitat")
sp2_net_plot

# Plot summary of % loss of current Suitable Habitat
sp1_summary = as.data.frame(c(sp1.loss.NA.2070,sp1.loss.MN.2070))
sp1_summary$year  = as.character(c(2070,2070))
sp1_summary$level = c('NA','MN')
names(sp1_summary) = c('Percent.Loss','Year','Region')

sp1_loss_plot = ggplot(sp1_summary, aes(fill=Year, y=Percent.Loss, x=Region)) + 
     geom_bar(position="dodge", stat="identity", fill = col1) +
     scale_fill_manual(values=c('#fc9272','#de2d26')) +
      theme(axis.text.x = element_text(face = "bold", size = 14)) +
      theme(axis.text.y = element_text(face = "bold", size = 14)) +
      theme(axis.title = element_text(face = "bold", size = 16)) + 
      theme(plot.title = element_text(face = "bold.italic", size = 24)) +
      ggtitle(species1) + labs(y="% Loss of Current Habitat")
sp1_loss_plot

sp2_summary = as.data.frame(c(sp2.loss.NA.2070,sp2.loss.MN.2070))
sp2_summary$year  = as.character(c(2070,2070))
sp2_summary$level = c('NA','MN')
names(sp2_summary) = c('Percent.Loss','Year','Region')

sp2_loss_plot = ggplot(sp2_summary, aes(fill=Year, y=Percent.Loss, x=Region)) + 
     geom_bar(position="dodge", stat="identity", fill = col2) +
     scale_fill_manual(values=c('#fc9272','#de2d26')) +
      theme(axis.text.x = element_text(face = "bold", size = 14)) +
      theme(axis.text.y = element_text(face = "bold", size = 14)) +
      theme(axis.title = element_text(face = "bold", size = 16)) + 
      theme(plot.title = element_text(face = "bold.italic", size = 24)) +
      ggtitle(species2) + labs(y="% Loss of Current Habitat")
sp2_loss_plot

```